src/Entity/Groupe.php
<?php

namespace App\Entity;

use App\Repository\GroupeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=GroupeRepository::class)
 * @UniqueEntity("name")
 * @UniqueEntity("type")
 */
class Groupe
{

    
    CONST TYPE = [
        'T0' => "Magasinier",
        'T1'=> "Livreur",
        'T2' => "Metteur en service",
        'T3' => "Acceptateur",
        'T4' => "Auditeur",
        'T5'=> "Installateur",
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $name;

 
    /**
     * @ORM\OneToMany(targetEntity=User::class, mappedBy="groupe")
     */
    private $users;

     /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $type;

    

    public function __construct()
    {
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->setGroupe($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->contains($user)) {
            $this->users->removeElement($user);
            // set the owning side to null (unless already changed)
            if ($user->getGroupe() === $this) {
                $user->setGroupe(null);
            }
        }

        return $this;
    }


    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }
    public function getTypeValue(): string
    {
      return self::TYPE[$this->type];
    }
}

src/Form/GroupeType.php
<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use  Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use App\Entity\Groupe;
use Symfony\Component\Validator\Constraints\Choice;

class GroupeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('name')
                ->add('type',ChoiceType::class,[
                     'choices'=>$this->getType(),
                     'placeholder' => 'Sélectionner un type',
                 ])
                ->add('save', SubmitType::class,['label' => 'Sauvegarder']);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Groupe::class,
        ]);
    }
    private function getType()
    {
        $type = Groupe:: TYPE;
        $output = [];
        foreach($type as $k =>$v){
            $output[$v] = $k;
        }
        return $output;
    }
}

src/Controller/Administration/FonctionController.php
<?php

namespace App\Controller\Administration;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use App\Entity\Fonction;
use App\Form\FonctionType;
use Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException;
use Knp\Component\Pager\PaginatorInterface;

class FonctionController extends AbstractController {


    /**
     * @Route("/fonction", name="fonction_page")
     */
    public function index(Request $request,PaginatorInterface $paginator){

        $em = $this->getDoctrine()->getManager();

        $search_input = !empty($request->get('search_input')) ? $request->get('search_input'):'';

        $page = !empty($request->get('page'))?$request->query->get('page'):1;

        $selected_row = !empty($request->get('selected_row'))?$request->query->get('selected_row'):'';

        $query = $em->getRepository(Fonction::class)->findBySearchInput($search_input);

        $pagination = $paginator->paginate(
            $query, /* query NOT result */
            $request->query->getInt('page', $page), /*page number*/
            10 /*limit per page*/
        );

        return $this->render('Administration/fonction/index.html.twig',[
            'current_menu'=>'fonction',
            'fonctions'=>$pagination,
            'search_input'=>$search_input,
            'selected_row'=>$selected_row,
            'page'=>$page,
            'action'=>'' // add or edit
        ]);
    }


    /**
     * @Route("/add_fonction", name="add_fonction_page")
     */
    public function add(Request $request,PaginatorInterface $paginator){

        $em = $this->getDoctrine()->getManager();

        $fonction = new Fonction();

        $form = $this->createForm(FonctionType::class,$fonction);
        
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){

            $em->persist($fonction);
            $em->flush();

            $this->addFlash('success', 'Un nouvel enregistrement est ajouté avec succès');
            
            return $this->redirectToRoute('fonction_page',array('selected_row'=>$fonction->getId()));
        }

        $query = $em->getRepository(Fonction::class)->findBySearchInput($search_input="");

        /*
hello
        */

        $pagination = $paginator->paginate(
            $query, /* query NOT result */
            $request->query->getInt('page', 1), /*page number*/
            10 /*limit per page*/
        );

        return $this->render('Administration/fonction/index.html.twig',[
            'current_menu'=>'fonction',
            'form'=>$form->createView(),
            'fonctions'=>$pagination,
            'search_input'=>'',
            'selected_row'=>'',
            'page'=>1,
            'action'=>'add'
        ]);

    }


    /**
     * @Route("/edit_fonction/{id}", name="edit_fonction_page")
     */
    public function update(Request $request,PaginatorInterface $paginator,$id){

        $em = $this->getDoctrine()->getManager();

        $search_input = !empty($request->get('search_input')) ? $request->get('search_input'):'';

        $page = !empty($request->get('page'))?$request->query->get('page'):1;

        $fonction = $em->getRepository(Fonction::class)->find($id);

        if(!$fonction){

            $this->addFlash('warning', 'Aucun enregistrement correspond à votre requête !');

            return $this->redirectToRoute('fonction_page');
        }

        $form = $this->createForm(FonctionType::class,$fonction);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){

            $em->flush();

            $this->addFlash('success', 'Cet enregistrement est modifié avec succès');
            
            return $this->redirectToRoute('fonction_page',array('selected_row'=>$fonction->getId(),'search_input'=>$search_input,'page'=>$page));
        }

        $query = $em->getRepository(Fonction::class)->findBySearchInput($search_input);

        $pagination = $paginator->paginate(
            $query, /* query NOT result */
            $request->query->getInt('page', $page), /*page number*/
            10 /*limit per page*/
        );

        return $this->render('Administration/fonction/index.html.twig',[
            'current_menu'=>'fonction',
            'form'=>$form->createView(),
            'fonctions'=>$pagination,
            'search_input'=>$search_input,
            'selected_row'=>$fonction->getId(),
            'page'=>$page,
            'action'=>'edit'
        ]);

    }

    /**
     * @Route("/delete_fonction",name="delete_fonction")
     */
    public function delete(Request $request){

        $id = $request->get('id');

        $em = $this->getDoctrine()->getManager();

        $fonction = $em->getRepository(Fonction::class)->find($id);

        try{ 
            
        $em->remove($fonction);

        $em->flush();

       $this->addFlash('success', 'Cet enregistrement est supprimé avec succés');

        return new Response(json_encode(array()),
            200,
            array('Content-Type'=>'application/json'));

        } catch (ForeignKeyConstraintViolationException $e) {

            $msg = "Cet enregistrement a des services connectés, il ne peut donc pas être supprimé !";

            return new Response(json_encode(array('msg'=>$msg)),
            201,
            array('Content-Type'=>'application/json'));
        }

    }


} // fin FonctionController

src/Controller/Administration/GroupeController.php
<?php

namespace App\Controller\Administration;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use App\Entity\Groupe;
use App\Form\GroupeType;
use Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException;
use Knp\Component\Pager\PaginatorInterface;

class GroupeController extends AbstractController {


    /**
     * @Route("/groupe", name="groupe_page")
     */
    public function index(Request $request,PaginatorInterface $paginator){

        $em = $this->getDoctrine()->getManager();

        $search_input = !empty($request->get('search_input')) ? $request->get('search_input'):'';

        $page = !empty($request->get('page'))?$request->query->get('page'):1;

        $selected_row = !empty($request->get('selected_row'))?$request->query->get('selected_row'):'';

        $query = $em->getRepository(Groupe::class)->findBySearchInput($search_input);

        $pagination = $paginator->paginate(
            $query, /* query NOT result */
            $request->query->getInt('page', $page), /*page number*/
            10 /*limit per page*/
        );

        return $this->render('Administration/groupe/index.html.twig',[
            'current_menu'=>'groupe',
            'groupes'=>$pagination,
            'search_input'=>$search_input,
            'selected_row'=>$selected_row,
            'page'=>$page,
            'action'=>'' // add or edit
        ]);
    }


    /**
     * @Route("/add_groupe", name="add_groupe_page")
     */
    public function add(Request $request,PaginatorInterface $paginator){

        $em = $this->getDoctrine()->getManager();

        $groupe = new Groupe();

        $form = $this->createForm(GroupeType::class,$groupe);
        
        $form->handleRequest($request);
        
        // $statut = $this->checkUnicityAuditeur($em,$groupe=NULL);

        if($form->isSubmitted() && $form->isValid() ){

            $em->persist($groupe);
            $em->flush();

            $this->addFlash('success', 'Un nouvel enregistrement est ajouté avec succès');
            
            return $this->redirectToRoute('groupe_page',array('selected_row'=>$groupe->getId()));
        }


        $query = $em->getRepository(Groupe::class)->findBySearchInput($search_input="");

        $pagination = $paginator->paginate(
            $query, /* query NOT result */
            $request->query->getInt('page', 1), /*page number*/
            10 /*limit per page*/
        );

        return $this->render('Administration/groupe/index.html.twig',[
            'current_menu'=>'groupe',
            'form'=>$form->createView(),
            'groupes'=>$pagination,
            'search_input'=>'',
            'selected_row'=>'',
            'page'=>1,
            'action'=>'add'
        ]);

    }


    /**
     * @Route("/edit_groupe/{id}", name="edit_groupe_page")
     */
    public function update(Request $request,PaginatorInterface $paginator,$id){

        $em = $this->getDoctrine()->getManager();

        $search_input = !empty($request->get('search_input')) ? $request->get('search_input'):'';

        $page = !empty($request->get('page'))?$request->query->get('page'):1;

        $groupe = $em->getRepository(Groupe::class)->find($id);

        if(!$groupe){

            $this->addFlash('warning', 'Aucun enregistrement correspond à votre requête !');

            return $this->redirectToRoute('groupe_page');
        }
      
       $form = $this->createForm(GroupeType::class,$groupe);

        $form->handleRequest($request);

        // $statut = $this->checkUnicityAuditeur($em,$groupe);

        if($form->isSubmitted() && $form->isValid()){
            
            $em->flush();

            $this->addFlash('success', 'Cet enregistrement est modifié avec succès');
            
            return $this->redirectToRoute('groupe_page',array('selected_row'=>$groupe->getId(),'search_input'=>$search_input,'page'=>$page));
        }


        $query = $em->getRepository(Groupe::class)->findBySearchInput($search_input);


        $pagination = $paginator->paginate(
            $query, /* query NOT result */
            $request->query->getInt('page', $page), /*page number*/
            10 /*limit per page*/
        );

        return $this->render('Administration/groupe/index.html.twig',[
            'current_menu'=>'groupe',
            'form'=>$form->createView(),
            'groupes'=>$pagination,
            'search_input'=>$search_input,
            'selected_row'=>$groupe->getId(),
            'page'=>$page,
            'action'=>'edit'
        ]);

    }

    /**
     * @Route("/delete_groupe",name="delete_groupe")
     */
    public function delete(Request $request){

        $id = $request->get('id');

        $em = $this->getDoctrine()->getManager();

        $groupe = $em->getRepository(Groupe::class)->find($id);

        try{ 
            
        $em->remove($groupe);

        $em->flush();

       $this->addFlash('success', 'Cet enregistrement est supprimé avec succés');

        return new Response(json_encode(array()),
            200,
            array('Content-Type'=>'application/json'));

        } catch (ForeignKeyConstraintViolationException $e) {

            $msg = "Cet enregistrement a des services connectés, il ne peut donc pas être supprimé !";

            return new Response(json_encode(array('msg'=>$msg)),
            201,
            array('Content-Type'=>'application/json'));
        }

    }

    // /*------------------------------------------------------------------*/
    // /*                   check unicity Auditeur                         */
    // /*------------------------------------------------------------------*/
    // private function checkUnicityAuditeur($em,$groupe){

    //     $statut = true;

    //     $checkAuditeur = $em->getRepository(Groupe::class)->checkUnicity($groupe);

    //     dump(sizeof($checkAuditeur));

    //     if(sizeof($checkAuditeur)>0){

    //         $this->addFlash('info','Vous ne pouvez pas avoir plus q\'un groupe avec le statut Auditeur');

    //         $statut = false;
    //     }

    //     return $statut;
    // }


} // fin GroupeController

templates/Administration/groupe/action.html.twig
{{ form_start(form, {'attr' :{'class' : 'form-disable', 'novalidate': 'novalidate', 'role': 'form'}}) }} 

        <div class="row">

            <div class="col-md-12">

                <div class="form-group m-b-40">

                    <label>Nom du groupe</label> : <span class=" text-danger">*</span>

                    <input type="text" class="form-control"   name="{{ form.name.vars.full_name}}" value="{{ form.name.vars.value }}" autofocus>

                    {% if not form.name.vars.valid %}

                        {% for error in form.name.vars.errors  %}

                            <span style="color:#f31313;"> {{ error.message }}</span>

                        {% endfor %}

                    {% endif %}

                    {% do form.name.setRendered %}

                </div>
            
        
            </div> <!-- end div name -->
              <div class="col-md-12">
             <div class="form-group m-b-40">

                         <label  for="input3">Type </label> : <span class=" text-danger">*</span>

                        {{ form_widget(form.type, {'attr' : {'class':'select2 form-control'}})}}
                       
                        {% if not form.type.vars.valid %}

                            {% for error in form.type.vars.errors  %}

                                <span class="help-block" style="color:#ffb22b;"> {{ error.message }}</span>

                            
                            {% endfor %}

                        {% endif %}
                  
                {% do form.type.setRendered %}

                </div>
        
            </div> <!-- end div name -->

            <div class="col-md-12">

                <a  class="btn btn-danger waves-effect pull-left text-white"
                    {% if action == "add" %} href="{{ path('groupe_page') }}" {% elseif action == "edit" %}
                     href="{{ path('groupe_page',{selected_row:selected_row,search_input:search_input,page:page}) }}" {% endif %}>Annuler
                </a>

                {{ form_widget(form.save, {'attr' :{'class':'btn btn-success pull-right'}})}}

            </div><!-- end div action -->

        </div><!-- end div row -->

{{ form_end(form) }}

templates/Administration/groupe/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} IT&M - Groupe utilisateur {% endblock %}


{% block body %}
    {{ parent() }}

    {% if action == "edit" or action == "add" %}
    <section class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h5>{% if action =="add" %} Nouvel {% else %} Modifier {% endif %} Enregistrement</h5>
                </div>
                <div class="card-body">
                    {{ include('Administration/groupe/action.html.twig') }}
                </div>
            </div>
        </div>
    </section>
    {% endif %}
    
    <section class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="bug-list-search-content">
                        <form method="get" action="">
                            <div class="position-relative">
                                <input type="search" id="search-contacts" name="search_input" value="{{ app.request.get('search_input')}}" class="form-control" placeholder="Recherche avancée...">
                                <div class="form-control-position">
                                    <i class="fa fa-search text-size-base text-muted la-rotate-270"></i>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h4 >Liste des Groupes Utilisateurs <span class="badge badge badge-info badge-pill mr-2">{{ groupes.getTotalItemCount }}</span></h4>
                    <div class="heading-elements mt-0">
                        {% if app.user and is_granted('ROLE_AJOUTER_GROUPE') %}
                            <a class="btn btn-cyan btn-sm" href="{{ path('add_groupe_page') }}"><i class="fa fa-plus mr-0"></i>
                                nouvel enregistrement
                            </a>
                        {% endif %}
                        <a class="btn btn-warning btn-sm" href="{{ path('groupe_page') }}" title="Actualiser"><i class="fa fa-refresh"></i></a>
                    </div> 
                </div>  <!-- end card-header -->
                <div class="card-body">
                    {% if not groupes|length %}

                        <div class="alert alert-info" role="alert" style="padding:8px;">
                            <i class="icon fa fa-info-circle"></i> <span id="content-message"> Aucun enregistrement trouvé</span>
                        </div>

                    {% else %}
                    <div class="table-responsive m-t-40">
                        <table class="display nowrap table table-hover table-bordered" cellspacing="0" width="100%" style="font-size:13.5px;">
                            <thead>
                            <tr>
                                <th>Nom du groupe</th>
                                <th>Type</th>
                                {% if app.user and (is_granted('ROLE_MODIFIER_GROUPE') or is_granted('ROLE_SUPPRIMER_GROUPE')) %}
                                <th style="text-align:center;">Actions</th>
                                {% endif %}
                            </tr>
                            </thead>
                            <tbody style="line-height:40px;">
                            {% for groupe in groupes %}
                                <tr data-id="{{ groupe.id }}" {% if groupe.id == selected_row %} style="Background-color:#dcdfdc;" {% endif %}>
                                    <td >{{ groupe.name }} </td>

                                      <td >{{ groupe.typeValue }}</td>
                                
                                    {% if app.user and (is_granted('ROLE_MODIFIER_GROUPE') or is_granted('ROLE_SUPPRIMER_GROUPE')) %}
                                    <td style="text-align: center; min-width:150px; width:120px;">
                                        {% if app.user and is_granted('ROLE_MODIFIER_GROUPE') %}
                                        <a class="btn btn-linkedin btn-sm"  href="{{ path('edit_groupe_page',{id:groupe.id,search_input:search_input,page:page}) }}" title="Modifier">
                                            <i class="fa fa-pencil-square-o text-white"></i>
                                        </a>
                                        {% endif %}
                                        {% if app.user and is_granted('ROLE_SUPPRIMER_GROUPE') %}
                                        <a class="btn btn-danger btn-sm" id="delete_data" data-id="{{ groupe.id }}" data-toggle="modal" data-target="#modal_delete_data" title="Supprimer">
                                            <i class="fa fa-trash-o text-white"></i>
                                        </a>
                                        {% endif %}
                                    </td>
                                    {% endif %}
                                </tr>
                            {% endfor %}

                            </tbody>
                        </table>
                        <div class="navigation pull-right" style="margin-left:20px;">
                            {{ knp_pagination_render(groupes) }}
                        </div>
                    </div><!-- end div table-responsive -->
                    {% endif  %}
                </div><!-- end div card-body -->
            </div><!-- end div card -->
        </div><!-- end div col-12 -->
    </section><!-- end div section -->

    <!--  start modal suppression data -->

    <div id="modal_delete_data" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-keyboard="false"
         data-backdrop="static">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel" style="color:#4b50fc">Suppression enregistrement</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                </div>
                 <div class="modal-body">
                    <p style="color:black;">Voulez vous vraiment supprimer cet enregistrement ?</p>
                </div>
                <div class="modal-footer">
                    <a class="btn btn-danger waves-effect" data-dismiss="modal" style="color:white;">Annuler</a>
                    <a  class="btn btn-success waves-effect" style="color:white;" id="confirmer_delete">Confirmer</a>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>

    <!--  end  modal suppression data -->


{% endblock %}


{% block javascripts %}
    {{ parent() }}

    <script type="text/javascript">

        {% for flash_message in app.session.flashBag.get('success') %}

                toastr.success('{{ flash_message }}', {positionClass: 'toast-top-center', containerId: 'toast-top-center'});

        {% endfor %}

        {% for flash_message in app.session.flashBag.get('info') %}

                toastr.info('{{ flash_message }}', {positionClass: 'toast-top-center', containerId: 'toast-top-center'});

        {% endfor %}


        {% for flash_message in app.session.flashBag.get('warning') %}

                toastr.warning('{{ flash_message }}', {positionClass: 'toast-top-center', containerId: 'toast-top-center'});

        {% endfor %}

        {% for flash_message in app.session.flashBag.get('error') %}

                toastr.error('{{ flash_message }}', {positionClass: 'toast-top-center', containerId: 'toast-top-center'});

        {% endfor %}


    </script>

    {% include('Administration/groupe/ajax/delete.html.twig') %}

{% endblock %}